name: Continuous Integration (CI)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - dependabot/*

  workflow_dispatch:

jobs:
  build-and-test-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Running linter
        run: npm run lint

      - name: Running the build
        run: |
          npm run build